import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { nextIndex, previousIndex, splitSentences } from './reader';
import './site.css';

const sample = `A dense page asks readers to hold several ideas at once. When attention slips, starting at the paragraph's beginning wastes energy. Listen Back Reader holds one sentence in view. Replay it, slow it down, or move forward when you are ready. The source page stays the source.`;
const sentences = splitSentences(sample);
type Route = '/' | '/demo' | '/privacy' | '/terms' | '/404';

function useRoute() {
  const get = (): Route => (['/', '/demo', '/privacy', '/terms'].includes(location.pathname) ? location.pathname : '/404') as Route;
  const [route, setRoute] = useState(get);
  useEffect(() => { const handler = () => setRoute(get()); addEventListener('popstate', handler); return () => removeEventListener('popstate', handler); }, []);
  const go = (path: string) => { history.pushState({}, '', path); setRoute(get()); };
  return { route, go };
}

function Header({ go }: { go: (path: string) => void }) {
 return <><a className="skip" href="#main">Skip to main content</a><header className="site-header"><a className="wordmark" href="/" onClick={(e) => {e.preventDefault();go('/')}}><i aria-hidden="true">◉</i> Listen Back</a><nav aria-label="Primary"><a href="/demo" onClick={(e)=>{e.preventDefault();go('/demo')}}>Demo</a><a href="#how">How it works</a><a href="/privacy" onClick={(e)=>{e.preventDefault();go('/privacy')}}>Privacy</a></nav></header></>;
}
function Footer({go}:{go:(path:string)=>void}) { return <footer className="site-footer"><p>Replay one sentence without losing your place.</p><nav aria-label="Footer"><a href="/privacy" onClick={e=>{e.preventDefault();go('/privacy')}}>Privacy</a><a href="/terms" onClick={e=>{e.preventDefault();go('/terms')}}>Terms</a><a href="https://sociobot.in" rel="external">Built by Param Factory</a></nav><small>v1.0.0 · Original illustration generated for this product.</small></footer>; }
function DemoBanner({reset,real}:{reset:()=>void;real:()=>void}) { return <aside className="demo-banner" aria-label="Demo mode"><span><b>Demo</b> — sample data, nothing is saved.</span><span><button onClick={reset}>Reset demo</button><button onClick={real}>Start for real</button></span></aside> }
function ReaderDemo() {
 const [index,setIndex]=useState(2); const [slow,setSlow]=useState(false); const [speaking,setSpeaking]=useState(false);
 const speak=()=>{ const sentence=sentences[index];if (!('speechSynthesis' in window)||!sentence) return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(sentence.text);u.rate=slow?.8:1;u.onend=()=>setSpeaking(false);setSpeaking(true);speechSynthesis.speak(u);};
 const previous=()=>{const n=previousIndex(index,sentences.length);setIndex(n);}; const next=()=>{const n=nextIndex(index,sentences.length);setIndex(n);};
 return <section className="reader-shell" aria-label="Sample reader"><div className="reader-top"><span className="source-dot">●</span><span>Sample article</span><span className="counter">Sentence {index+1} / {sentences.length}</span></div><article className="sample-text">{sentences.map((sentence) => <p key={sentence.id} className={sentence.id === index ? 'active-sentence' : undefined} aria-current={sentence.id === index ? 'true' : undefined}>{sentence.text}</p>)}</article><div className="reader-controls"><button onClick={previous} aria-label="Previous sentence">←<small>Back</small></button><button className="listen" onClick={speak}>{speaking?'Reading…':'Read sentence'}<small>Alt + R replays</small></button><button onClick={next} aria-label="Next sentence">→<small>Next</small></button><button onClick={()=>setSlow(!slow)}>{slow?'1×':'0.8×'}<small>{slow?'Normal':'Slow'}</small></button></div></section>;
}
function Home({go}:{go:(p:string)=>void}){return <><main id="main" tabIndex={-1}><section className="hero"><div className="hero-copy"><p className="kicker">A browser extension for steady reading</p><h1 tabIndex={-1}>Replay each sentence. Keep your place.</h1><p className="lede">For readers who lose their place in dense web text.</p><div className="actions"><a className="primary" href="/demo" onClick={e=>{e.preventDefault();go('/demo')}}>Try it with sample data</a><span>Hear a sample sentence now.</span></div><ul className="facts"><li>Uses your browser's voice.</li><li>Text stays on your device.</li><li>Free and account-free.</li></ul></div><figure><img src="/hero.webp" srcSet="/hero-mobile.webp 768w, /hero.webp 1536w" sizes="(max-width: 700px) calc(100vw - 32px), 45vw" width="1536" height="1024" fetchPriority="high" decoding="async" alt="An ink-and-paper illustration of a marked article sentence looping back through sound waves." /><figcaption>Original print-style illustration for Listen Back Reader.</figcaption></figure></section><section className="product-preview" aria-labelledby="preview-heading"><div><p className="kicker">The reading loop</p><h2 id="preview-heading">One sentence stays visible while you listen.</h2><p>The extension marks the source sentence. Replay it until it lands, then move one sentence at a time.</p></div><ReaderDemo/></section><section id="how" className="how" aria-labelledby="how-heading"><p className="kicker">How it works</p><h2 id="how-heading">Read web text in three steady steps.</h2><ol><li><b>Open an article.</b><span>Choose a page with the text you want to hear.</span></li><li><b>Read the sentence.</b><span>Listen Back finds readable page text and marks the current sentence.</span></li><li><b>Replay or move on.</b><span>Use the popup or Alt + R, Alt + Left, and Alt + Right.</span></li></ol></section><section className="limits"><div><p className="kicker">What it does not do</p><h2>It reads the source. It does not rewrite it.</h2></div><p>Listen Back does not upload page text, diagnose dyslexia, create voices, or save an account. It does not read pages that explicitly block copying.</p></section><section className="download"><p className="kicker">Use it on ordinary web pages</p><h2>Install the free extension.</h2><p>Download the packaged extension, then load it in your browser’s extension developer mode.</p><a className="primary" href="/downloads/listen-back-reader.zip" download>Download extension zip</a></section></main></>}
function Demo({go}:{go:(path:string)=>void}){const [key,setKey]=useState(0);return <><DemoBanner reset={()=>setKey(k=>k+1)} real={()=>go('/')}/><main id="main" tabIndex={-1} className="demo-page"><p className="kicker">A private sample</p><h1 tabIndex={-1}>Hear one sentence at a time.</h1><p className="lede">This sample uses browser speech only. Nothing is stored.</p><ReaderDemo key={key}/><p className="help">Use the buttons to move through the sample. Install the extension to mark sentences on any readable web article.</p></main></>}
function Legal({kind}:{kind:'privacy'|'terms'}){const privacy=kind==='privacy';return <main id="main" tabIndex={-1} className="legal"><p className="kicker">Listen Back Reader</p><h1 tabIndex={-1}>{privacy?'Privacy is local by default.':'Simple terms for a free reader.'}</h1>{privacy?<><h2>No accounts or analytics</h2><p>The extension uses your browser’s speech service. It does not send article text to a Listen Back server.</p><h2>What stays in your browser</h2><p>The current sentence and speed stay in memory while you read. The extension does not create a reading history.</p><h2>Page permission</h2><p>The extension reads visible article text on ordinary pages to prepare its controls. It skips pages that explicitly block copying.</p></>:<><h2>Use the source responsibly</h2><p>Listen Back reads text already shown in your browser. You are responsible for following a site’s terms and copyright rules.</p><h2>No guarantee of availability</h2><p>Browser speech voices and page layouts vary. The extension is provided free, as available.</p></>}</main>}
function NotFound({go}:{go:(p:string)=>void}){return <main id="main" tabIndex={-1} className="legal not-found"><p className="kicker">Ink lost its line</p><h1 tabIndex={-1}>This page is not in the reader.</h1><p>Go back to the place where the sentence starts.</p><button className="primary" onClick={()=>go('/')}>Go to home</button></main>}
function App(){const {route,go}=useRoute();useEffect(()=>{document.title=route==='/demo'?'Demo — Listen Back Reader':route==='/privacy'?'Privacy — Listen Back Reader':route==='/terms'?'Terms — Listen Back Reader':route==='/404'?'Page not found — Listen Back Reader':'Listen Back Reader — replay one sentence';requestAnimationFrame(()=>document.querySelector<HTMLHeadingElement>('main h1')?.focus());},[route]);return <><Header go={go}/>{route==='/'?<Home go={go}/>:route==='/demo'?<Demo go={go}/>:route==='/privacy'?<Legal kind="privacy"/>:route==='/terms'?<Legal kind="terms"/>:<NotFound go={go}/>}<Footer go={go}/><div className="route-live" aria-live="polite">{route==='/'?'Home':route.slice(1)||'Home'} page</div></>}
createRoot(document.getElementById('root')!).render(<App/>);
